### ISSUE TITLE
Add service identifier file

### ISSUE THREAD

**Issue by ennerf** [Paullo612/mlfx#22]
If your annotation processor includes a `META-INF/services/javax.annotation.processing.Processor` service file you can omit the manual setup in the compiler plugin. I usually use [AutoService](https://github.com/google/auto/tree/main/service) to automatically generate it and keep it in sync, e.g.,

```xml
<dependency>
    <groupId>com.google.auto.service</groupId>
    <artifactId>auto-service</artifactId> 
    <version>1.0.1</version>
    <scope>compile</scope>
</dependency>
```

```java
import com.google.auto.service.AutoService;
import javax.annotation.processing.Processor;

@AutoService(Processor.class)
public class MyAnnotationProcessor extends AbstractProcessor {
  /* ... */
}
```

**Comment by Paullo612** [comment]
Annotation processor is registered by Micronaut, and mlfx is registered in Micronaut through `ServiceLoader`. So, service loader's services can definitely be registered through google's `AutoService`.

**Comment by Paullo612** [comment]
Done.
