### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by ennerf** [Paullo612/mlfx#23]
Thanks for doing this project! I was actually thinking about doing something similar for the same reason, so hopefully I'll just be able to just use this.

I just tried it on a project, but unfortunately I didn't get any of the generated FXML classes. The micronaut accessors were generated as expected though. I'm on Windows, so it might be related to the Windows path issue.

Overall, it's a bit difficult to figure everything out from the test code (e.g. path conventions, absolute vs relative paths, etc.). It'd be great if you could set up a tiny sample project that includes a JavaFX application w/ FXML.

I'm also not clear on where the `micronaut.mlfx.resourcesDirectory` annotation processor option is supposed to go. Should that be set in the compiler plugin? in the maven properties section? I've never used Micronaut before.

**Comment by Paullo612** [comment]
>  I'm on Windows, so it might be related to the Windows path issue.

Yeah, I've tried compiling in Windows, but it was long time ago. Looks like I've broken something. Will fix that and publish a new release in meantime.

> I'm also not clear on where the micronaut.mlfx.resourcesDirectory annotation processor option is supposed to go.

`micronaut.mlfx.resourcesDirectory` is for specifying path to your resources directory (for simple Maven setup, if your resources are in `src/main/resources`) it is not needed. Here is an example for completeness:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        ...
        <compilerArgs combine.children="append">
            <arg>-Amicronaut.mlfx.resourcesDirectory=./resources</arg>
        </compilerArgs>
        ...
    </configuration>
<plugin>
```

**Comment by Paullo612** [comment]
Added a [link](https://github.com/Paullo612/mlfx/blob/fe38709c2111321c51919000f37e605c5f7212db/README.md?plain=1#L115) to sample project. So, closing this.

**Comment by ennerf** [comment]
Looks good, thanks!
